debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.hellpyending: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mariadb://rc4-pedro-server-db.cuupyzlcppur.ap-northeast-2.rds.amazonaws.com/hellpyending?useSSL=false&autoReconnect=true&validationQuery=select 1
    username: tigershrimp
    password: TigerShrimp1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
