debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.hellpyending: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/hellpyending?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
#    username: "root"
#    password: "0000"
#    driver-class-name: org.mariadb.jdbc.Driver

spring:
  datasource:
    url: jdbc:mariadb://rc4-pedro-server-db.cuupyzlcppur.ap-northeast-2.rds.amazonaws.com/hellpyending?useSSL=false&autoReconnect=true&validationQuery=select 1
    username: tigershrimp
    password: TigerShrimp1!
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "621627849576689"
            client-secret: "0b2322fc2c9f80fa9ec32659ba24258c"
          google:
            client-id: "386877204084-s4t7rabkfc9io6sgr74hothplrl3el5t.apps.googleusercontent.com"
            client-secret: "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"

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always


cloud:
  aws:
    credentials:
      accessKey: AKIA6LTTW3X7YFHZJ4QE       # AWS IAM AccessKey 적기
      secretKey: rqJw9EKz4hCvjS8Cad3xrqA0tNF0cpoLUWKPddjm  # AWS IAM SecretKey 적기
    s3:
      bucket: tigershrimp-bucket    # ex) marryting-gyunny
      dir: ImageUrl/ # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false
